import gdb
LX_CONFIG_DEBUG_INFO_REDUCED = 0
if 1:
    LX_CLK_GET_RATE_NOCACHE = gdb.parse_and_eval("((((1UL))) << (6))")
LX_SB_RDONLY = gdb.parse_and_eval("((((1UL))) << (0))")
LX_SB_SYNCHRONOUS = gdb.parse_and_eval("((((1UL))) << (4))")
LX_SB_MANDLOCK = gdb.parse_and_eval("((((1UL))) << (6))")
LX_SB_DIRSYNC = gdb.parse_and_eval("((((1UL))) << (7))")
LX_SB_NOATIME = gdb.parse_and_eval("((((1UL))) << (10))")
LX_SB_NODIRATIME = gdb.parse_and_eval("((((1UL))) << (11))")
LX_hrtimer_resolution = gdb.parse_and_eval("hrtimer_resolution")
LX_IRQD_LEVEL = gdb.parse_and_eval("IRQD_LEVEL")
LX_IRQ_HIDDEN = gdb.parse_and_eval("IRQ_HIDDEN")
LX_MOD_TEXT = gdb.parse_and_eval("MOD_TEXT")
LX_MNT_NOSUID = 0x01
LX_MNT_NODEV = 0x02
LX_MNT_NOEXEC = 0x04
LX_MNT_NOATIME = 0x08
LX_MNT_NODIRATIME = 0x10
LX_MNT_RELATIME = 0x20
LX_NR_CPUS = 8192
LX_OF_DT_HEADER = 0xd00dfeed
LX_RADIX_TREE_ENTRY_MASK = gdb.parse_and_eval("3UL")
LX_RADIX_TREE_INTERNAL_NODE = gdb.parse_and_eval("2UL")
LX_RADIX_TREE_MAP_SIZE = gdb.parse_and_eval("(1UL << (0 ? 4 : 6))")
LX_RADIX_TREE_MAP_SHIFT = gdb.parse_and_eval("(0 ? 4 : 6)")
LX_RADIX_TREE_MAP_MASK = gdb.parse_and_eval("((1UL << (0 ? 4 : 6))-1)")
LX_CONFIG_GENERIC_CLOCKEVENTS = 1
LX_CONFIG_GENERIC_CLOCKEVENTS_BROADCAST = 1
LX_CONFIG_HIGH_RES_TIMERS = 1
LX_CONFIG_NR_CPUS = 0
LX_CONFIG_OF = 0
LX_CONFIG_TICK_ONESHOT = 1
LX_CONFIG_GENERIC_IRQ_SHOW_LEVEL = 0
LX_CONFIG_X86_LOCAL_APIC = 1
LX_CONFIG_SMP = 1
LX_CONFIG_X86_THERMAL_VECTOR = 1
LX_CONFIG_X86_MCE_THRESHOLD = 1
LX_CONFIG_X86_MCE_AMD = 1
LX_CONFIG_X86_MCE = 1
LX_CONFIG_X86_IO_APIC = 1
LX_CONFIG_HAVE_KVM = 1
